### ISSUE TITLE
App Creation Failed on Heroku

### ISSUE THREAD

**Issue by safe-mint** [nftchance/longtails#6]
After trying to create an app on Heroku, I get the error "App creation failed. Please ensure you have valid values in the above form fields."  All my fields are filled with correct values.  Is there any way to debug / see logs without rebuilding it locally? (I am not really a python/django programmer).

<img width="679" alt="image" src="https://user-images.githubusercontent.com/99052729/184553519-e0a98c68-2632-41ae-808a-c8d46ad220bb.png">

**Comment by 381e35** [comment]
Unfortunately, Heroku deploy actions aren't super UX-focused as they make the assumption that everything is running correctly (so they don't share the "create app" logs) and only process logs once the app has been created (which is currently being prevented)

You could go to Heroku and create a project built off the forked repository, and then you would have access to all the logs (since the app would already be created and a build action would just be ran.)

I will check it out though, if you setup all the environment variables, everything _should_ work fine. Which means there's likely an issue somewhere in the repo.

**Comment by 381e35** [comment]
For posterity, it does run locally so I can 100% confirm it is a Heroku deployment issue -- Should be relatively simple to find the fix.

**Comment by 381e35** [comment]
Alright, @safe-mint. Update has been pushed that "should" allow you just to click the button, enter the values and get it running to the point where you don't need to do anything.

Previously, you still would've had to increase the processes running, so I went ahead and also updated that. Let me know if everything is all groovy for ya :)

For future reference, if you have any issues you can access Heroku logs in-terminal with:

```
heroku logs --tail -a <app-name>
```

**Comment by safe-mint** [comment]
thank you @nftchance ! working now

<img width="679" alt="image" src="https://user-images.githubusercontent.com/99052729/184556085-7a9d6b43-cfca-42a4-bac8-fc45d891d6b5.png">
